tt-torch model test parser
tenstorrent/tt-github-actions pull request #8
Opened 2024-12-03 03:38 UTC by nsmithtt

2024-12-03 03:38 UTC, nsmithtt commented
@vmilosevic / @AleksKnezevic / @ddilbazTT / @uazizTT

2024-12-03 13:45 UTC, AleksKnezevic approved these changes

2024-12-03 14:44 UTC, vmilosevic approved these changes
Can you include test for TTTorchModelTestsParser? Simple test is enough, process one file and assert that number of discovered tests is correct.

2024-12-03 14:44 UTC, vmilosevic commented on .github/actions/collect_data/src/parsers/tt_torch_model_tests_parser.py
> +from functools import partial
Please remove unused imports partial and junit_xml_utils

2024-12-03 14:49 UTC, vmilosevic requested changes
.

2024-12-04 00:41 UTC, warthog9 commented
No issues from my side

2024-12-04 12:10 UTC, vmilosevic approved these changes

2024-12-04 12:20 UTC, vmilosevic commented
@nsmithtt  The error you see in the workflow is because you are making a PR from the fork, and it doesn't have permission to add comments to PR to show the report.

We can ignore this, easiest way to get around this is by adding "continue-on-error: true" to "Show reports" step

File .github/workflows/test_collect_data_action.yml Line 37 add 
continue-on-error: true

2024-12-04 16:31 UTC, merged